GET http://localhost:8000/api/course
###
GET http://localhost:8000/api/course/1
###
POST http://localhost:8000/api/course
Content-Type: application/json

{
    "icon_id": 0,
    "name": "lorem ipsum",
    "page_url": "lorem ipsum",
    "description": "lorem ipsum",
    "occupation_area": "lorem ipsum",
    "area": "lorem ipsum",
    "workload": "lorem ipsum",
    "duration": "lorem ipsum",
    "local": "lorem ipsum",
    "course_types": "lorem ipsum",
    "mode": "lorem ipsum"
}